"""Title column added

Revision ID: a6227f7ed900
Revises: 90532f821ce3
Create Date: 2024-11-24 21:53:03.338870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6227f7ed900'
down_revision = '90532f821ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
